# Mission Configuration for Data Scout Agent
# This file contains the mission parameters and configuration for the Data Scout Agent, separated from the main claimify config.

search_provider: "brave/search"
recursion_per_sample: 30
initial_prompt: |
  Begin the data prospecting mission based on your configured mission plan.

nodes:
  research:
    max_iterations: 7

mission_plan:
  goal: "Find reliable, verifiable data sources to build a training corpus about the safety and efficacy of GLP-1 agonists for weight loss."
  nodes:
    - name: "supervisor"
      model: "openai/gpt-5-mini"
      temperature: 1
      max_tokens: 65536
    - name: "research"
      model: "openai/gpt-5-mini"
      temperature: 1
      max_tokens: 65536
    - name: "fitness"
      model: "openai/gpt-5-mini"
      temperature: 1
      max_tokens: 65536
    - name: "archive"
      model: "openai/gpt-5-mini"
      temperature: 1
      max_tokens: 65536
    - name: "synthetic"
      model: "openai/gpt-5-mini"
      temperature: 1
      max_tokens: 65536

writer:
  tier1_path: "examples/data/datasets/tier1"
  tier2_path: "examples/data/datasets/tier2"
  audit_trail_path: "examples/PEDIGREE.md"

checkpointer_path: ".checkpointer.sqlite"
