[project]
name = "aclarai-claimify"
version = "0.1.0"
dependencies = [
    "llama-index-core",
    "llama-index-llms-openai",
    "pyyaml",
]

[project.optional-dependencies]
dev = [
    "pytest",
]

[tool.setuptools]
packages = ["aclarai_claimify"]