# Mission Configuration for Data Scout Agent
# This file contains the mission parameters and configuration for the Data Scout Agent, separated from the main claimify config.

search_provider: "google/search"
recursion_per_sample: 35 # 11 allows for 2 retries at research (4n + 3)
initial_prompt: |
  Begin the data prospecting mission based on your configured mission plan.

# Observability configuration for LangSmith
# You can also set these via environment variables:
# - LANGCHAIN_API_KEY or LANGSMITH_API_KEY (required for tracing)
# - LANGCHAIN_TRACING_V2 or LANGSMITH_TRACING (enable/disable tracing)
# - LANGCHAIN_ENDPOINT or LANGSMITH_ENDPOINT (custom endpoint)
# - LANGCHAIN_PROJECT or LANGSMITH_PROJECT (project name)
#
# Note: LiteLLM may show a non-blocking error about logger initialization when the scout
# agent starts. This is expected behavior and does not affect functionality - LangSmith
# tracing will work correctly despite this initial error message. The error occurs because 
# LiteLLM tries to initialize its custom logger during import, but in subprocess contexts 
# there may not be an event loop available yet. This is purely informational and can be ignored.
observability:
  tracing: true  # Enable/disable tracing
  # api_key: "your-langsmith-api-key"  # Not recommended in config files, use environment variables instead
  endpoint: "https://api.smith.langchain.com"  # Custom endpoint for self-hosted deployments
  project: "aclarai-claimify-scout"  # Project name for organizing traces

nodes:
  research:
    max_iterations: 7

mission_plan:
  goal: "Find reliable, verifiable data sources to build a training corpus about the safety and efficacy of GLP-1 agonists for weight loss."
  nodes:
    - name: "supervisor"
      model: "openai/gpt-5-mini"
      temperature: 1
      max_tokens: 65536
    - name: "research"
      model: "openai/gpt-5-mini"
      temperature: 1
      max_tokens: 65536
    - name: "fitness"
      model: "openai/gpt-5-mini"
      temperature: 1
      max_tokens: 65536
    - name: "archive"
      model: "openai/gpt-5-mini"
      temperature: 1
      max_tokens: 65536
    - name: "synthetic"
      model: "openai/gpt-5-mini"
      temperature: 1
      max_tokens: 65536

writer:
  tier1_path: "examples/data/datasets/tier1"
  tier2_path: "examples/data/datasets/tier2"
  audit_trail_path: "examples/PEDIGREE.md"

checkpointer_path: ".checkpointer.sqlite"
