window:
  claimify:
    p: 3
    f: 1

model:
  claimify:
    selection: "openai/gpt-4o-mini"
    disambiguation: "openai/gpt-4o-mini"
    decomposition: "openai/gpt-4o-mini"
    default: "openai/gpt-4o-mini"
  fallback_plugin: "openai/gpt-4o-mini"

processing:
  claimify:
    max_retries: 3
    logging:
      log_decisions: true
      log_transformations: true
      log_timing: true
  timeout_seconds: 600
  temperature: 0.1
  max_tokens: 1000

generate_dataset:
  # User can choose the context generation method. Options: "semantic" or "static"
  method: "semantic"

  # Parameters for the "semantic" method
  semantic:
    embedder:
      # Specifies which plugin to use from aclarai_claimify/embeddings/
      type: "sentence_transformer"
      model: "all-MiniLM-L6-v2"
    context_params:
      min_k: 3
      max_k: 20
      similarity_threshold: 0.75

  # Parameters for the "static" method (the old behavior)
  static:
    k_window_size: 3 # The number of sentences before/after

scout_agent:
  search_provider: "brave/search"
  initial_prompt: |
    Begin the data prospecting mission based on your configured mission plan.
  nodes:
    research:
      max_iterations: 7
  mission_plan:
    goal: "Find reliable, verifiable data sources to build a training corpus about the safety and efficacy of GLP-1 agonists for weight loss."
    nodes:
      - name: "supervisor"
        model: "openai/gpt-5-mini"
        temperature: 1
        max_tokens: 65536
      - name: "research"
        model: "openai/gpt-5-mini" # Used for generating search queries
        temperature: 1
        max_tokens: 65536
      - name: "fitness"
        model: "openai/gpt-5-mini" # Highest-quality model for evaluation
        temperature: 1
        max_tokens: 65536
      - name: "archive"
        model: "openai/gpt-5-mini" # Not an LLM call, but can be configured
        temperature: 1
        max_tokens: 65536
      - name: "synthetic"
        model: "openai/gpt-5-mini"
        temperature: 1
        max_tokens: 65536
  writer:
    tier1_path: "examples/data/datasets/tier1"
    tier2_path: "examples/data/datasets/tier2"
    audit_trail_path: "examples/PEDIGREE.md"
  checkpointer_path: ".checkpointer.sqlite"