window:
  claimify:
    p: 3
    f: 1

model:
  claimify:
    selection: "openai/gpt-5-mini"
    disambiguation: "openai/gpt-5-mini"
    decomposition: "openai/gpt-5-mini"
    default: "openai/gpt-5-mini"
  fallback_plugin: "openai/gpt-5-mini"

processing:
  claimify:
    max_retries: 3
    logging:
      log_decisions: true
      log_transformations: true
      log_timing: true
  timeout_seconds: 600
  temperature: 0.1
  max_tokens: 1000

generate_dataset:
  # User can choose the context generation method. Options: "semantic" or "static"
  method: "semantic"

  # Parameters for the "semantic" method
  semantic:
    embedder:
      # Specifies which plugin to use from aclarai_claimify/embeddings/
      type: "sentence_transformer"
      model: "all-MiniLM-L6-v2"
    context_params:
      min_k: 3
      max_k: 20
      similarity_threshold: 0.75

  # Parameters for the "static" method (the old behavior)
  static:
    k_window_size: 3 # The number of sentences before/after