window:
  claimify:
    p: 3
    f: 1

model:
  claimify:
    selection: "gpt-4o-mini"
    disambiguation: "gpt-4o-mini"
    decomposition: "gpt-4o-mini"
    default: "gpt-4o-mini"
  fallback_plugin: "gpt-4o-mini"

processing:
  claimify:
    max_retries: 3
    logging:
      log_decisions: true
      log_transformations: true
      log_timing: true
  timeout_seconds: 30
  temperature: 0.1
  max_tokens: 1000

# NEW SECTION for the generate-dataset tool
generate_dataset:
  # User can choose the context generation method. Options: "semantic" or "static"
  method: "semantic"

  # Parameters for the "semantic" method
  semantic:
    embedder:
      # Specifies which plugin to use from aclarai_claimify/embeddings/
      type: "sentence_transformer"
      model: "all-MiniLM-L6-v2"
    context_params:
      min_k: 3
      max_k: 20
      similarity_threshold: 0.75

  # Parameters for the "static" method (the old behavior)
  static:
    k_window_size: 3 # The number of sentences before/after

# NEW SECTION for the Data Scout Agent
scout_agent:
  mission_plan:
    goal: "Find reliable, verifiable data sources to build a training corpus about the safety and efficacy of GLP-1 agonists for weight loss."
    max_iterations: 5
    nodes:
      - name: "DeconstructGoalNode"
        model: "claude-3-haiku-20240307"
        temperature: 0.1
        max_tokens: 2048
      - name: "PlanNode"
        model: "claude-3-haiku-20240307"
        temperature: 0.1
        max_tokens: 4096
      - name: "WebSearchNode"
        model: "claude-3-haiku-20240307" # Used for generating search queries
        temperature: 0.2
        max_tokens: 1024
      - name: "FitnessCheckNode"
        model: "claude-3-opus-20240229" # Highest-quality model for evaluation
        temperature: 0.0
        max_tokens: 2048
      - name: "ArchivingNode"
        model: "claude-3-haiku-20240307" # Not an LLM call, but can be configured
        temperature: 0.0
        max_tokens: 0
  writer:
    tier1_path: "scout_tier1_raw"
    tier2_path: "scout_tier2_curated"
    audit_trail_path: "PEDIGREE.md"
  checkpointer_path: ".checkpointer.sqlite"
