window:
  claimify:
    p: 3
    f: 1

model:
  claimify:
    selection: "gpt-4o-mini"
    disambiguation: "gpt-4o-mini"
    decomposition: "gpt-4o-mini"
    default: "gpt-4o-mini"
  fallback_plugin: "gpt-4o-mini"

processing:
  claimify:
    max_retries: 3
    logging:
      log_decisions: true
      log_transformations: true
      log_timing: true
  timeout_seconds: 30
  temperature: 0.1
  max_tokens: 1000